// <copyright file="MainForm.Designer.cs" company="PUblicDomain.com">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace Urlister
{
    partial class MainForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
        	System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
        	this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
        	this.minimizeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.fileToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
        	this.newToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.openToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator = new System.Windows.Forms.ToolStripSeparator();
        	this.saveToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.saveAsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
        	this.exitToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
        	this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.cutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.copyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.pasteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.deleteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator5 = new System.Windows.Forms.ToolStripSeparator();
        	this.selectAllToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.alwaysOnTopToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.closeBrowserToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.saveSettingsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.moreReleasesPublicDomainGiftcomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.originalThreadDonationCodercomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.sourceCodeGithubcomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
        	this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.mainStatusStrip = new System.Windows.Forms.StatusStrip();
        	this.mainToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.lineCounToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
        	this.mainTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
        	this.browseLabel = new System.Windows.Forms.Label();
        	this.browserComboBox = new System.Windows.Forms.ComboBox();
        	this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
        	this.beginButton = new System.Windows.Forms.Button();
        	this.backButton = new System.Windows.Forms.Button();
        	this.playButton = new System.Windows.Forms.Button();
        	this.nextButton = new System.Windows.Forms.Button();
        	this.endButton = new System.Windows.Forms.Button();
        	this.intervalNumericUpDown = new System.Windows.Forms.NumericUpDown();
        	this.label1 = new System.Windows.Forms.Label();
        	this.urlListtextBox = new System.Windows.Forms.TextBox();
        	this.openFileDialog = new System.Windows.Forms.OpenFileDialog();
        	this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
        	this.mainMenuStrip.SuspendLayout();
        	this.mainStatusStrip.SuspendLayout();
        	this.mainTableLayoutPanel.SuspendLayout();
        	this.tableLayoutPanel2.SuspendLayout();
        	((System.ComponentModel.ISupportInitialize)(this.intervalNumericUpDown)).BeginInit();
        	this.SuspendLayout();
        	// 
        	// mainMenuStrip
        	// 
        	this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.minimizeToolStripMenuItem,
        	        	        	this.fileToolStripMenuItem1,
        	        	        	this.editToolStripMenuItem,
        	        	        	this.optionsToolStripMenuItem,
        	        	        	this.helpToolStripMenuItem});
        	this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
        	this.mainMenuStrip.Name = "mainMenuStrip";
        	this.mainMenuStrip.Size = new System.Drawing.Size(284, 24);
        	this.mainMenuStrip.TabIndex = 23;
        	// 
        	// minimizeToolStripMenuItem
        	// 
        	this.minimizeToolStripMenuItem.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
        	this.minimizeToolStripMenuItem.Name = "minimizeToolStripMenuItem";
        	this.minimizeToolStripMenuItem.Size = new System.Drawing.Size(12, 20);
        	this.minimizeToolStripMenuItem.Visible = false;
        	// 
        	// fileToolStripMenuItem1
        	// 
        	this.fileToolStripMenuItem1.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.newToolStripMenuItem,
        	        	        	this.openToolStripMenuItem,
        	        	        	this.toolStripSeparator,
        	        	        	this.saveToolStripMenuItem,
        	        	        	this.saveAsToolStripMenuItem,
        	        	        	this.toolStripSeparator1,
        	        	        	this.exitToolStripMenuItem1});
        	this.fileToolStripMenuItem1.Name = "fileToolStripMenuItem1";
        	this.fileToolStripMenuItem1.Size = new System.Drawing.Size(37, 20);
        	this.fileToolStripMenuItem1.Text = "&File";
        	// 
        	// newToolStripMenuItem
        	// 
        	this.newToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("newToolStripMenuItem.Image")));
        	this.newToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.newToolStripMenuItem.Name = "newToolStripMenuItem";
        	this.newToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
        	this.newToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.newToolStripMenuItem.Text = "&New";
        	this.newToolStripMenuItem.Click += new System.EventHandler(this.OnNewToolStripMenuItemClick);
        	// 
        	// openToolStripMenuItem
        	// 
        	this.openToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("openToolStripMenuItem.Image")));
        	this.openToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.openToolStripMenuItem.Name = "openToolStripMenuItem";
        	this.openToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.O)));
        	this.openToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.openToolStripMenuItem.Text = "&Open";
        	this.openToolStripMenuItem.Click += new System.EventHandler(this.OnOpenToolStripMenuItemClick);
        	// 
        	// toolStripSeparator
        	// 
        	this.toolStripSeparator.Name = "toolStripSeparator";
        	this.toolStripSeparator.Size = new System.Drawing.Size(143, 6);
        	this.toolStripSeparator.Visible = false;
        	// 
        	// saveToolStripMenuItem
        	// 
        	this.saveToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("saveToolStripMenuItem.Image")));
        	this.saveToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
        	this.saveToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)));
        	this.saveToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.saveToolStripMenuItem.Text = "&Save ";
        	this.saveToolStripMenuItem.Click += new System.EventHandler(this.OnSaveToolStripMenuItemClick);
        	// 
        	// saveAsToolStripMenuItem
        	// 
        	this.saveAsToolStripMenuItem.Name = "saveAsToolStripMenuItem";
        	this.saveAsToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
        	this.saveAsToolStripMenuItem.Text = "Save &As";
        	this.saveAsToolStripMenuItem.Visible = false;
        	// 
        	// toolStripSeparator1
        	// 
        	this.toolStripSeparator1.Name = "toolStripSeparator1";
        	this.toolStripSeparator1.Size = new System.Drawing.Size(143, 6);
        	// 
        	// exitToolStripMenuItem1
        	// 
        	this.exitToolStripMenuItem1.Name = "exitToolStripMenuItem1";
        	this.exitToolStripMenuItem1.Size = new System.Drawing.Size(146, 22);
        	this.exitToolStripMenuItem1.Text = "E&xit";
        	this.exitToolStripMenuItem1.Click += new System.EventHandler(this.OnExitToolStripMenuItem1Click);
        	// 
        	// editToolStripMenuItem
        	// 
        	this.editToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.cutToolStripMenuItem,
        	        	        	this.copyToolStripMenuItem,
        	        	        	this.pasteToolStripMenuItem,
        	        	        	this.deleteToolStripMenuItem,
        	        	        	this.toolStripSeparator5,
        	        	        	this.selectAllToolStripMenuItem});
        	this.editToolStripMenuItem.Name = "editToolStripMenuItem";
        	this.editToolStripMenuItem.Size = new System.Drawing.Size(39, 20);
        	this.editToolStripMenuItem.Text = "&Edit";
        	// 
        	// cutToolStripMenuItem
        	// 
        	this.cutToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("cutToolStripMenuItem.Image")));
        	this.cutToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.cutToolStripMenuItem.Name = "cutToolStripMenuItem";
        	this.cutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.X)));
        	this.cutToolStripMenuItem.Size = new System.Drawing.Size(144, 22);
        	this.cutToolStripMenuItem.Text = "Cu&t";
        	this.cutToolStripMenuItem.Click += new System.EventHandler(this.OnCutToolStripMenuItemClick);
        	// 
        	// copyToolStripMenuItem
        	// 
        	this.copyToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("copyToolStripMenuItem.Image")));
        	this.copyToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.copyToolStripMenuItem.Name = "copyToolStripMenuItem";
        	this.copyToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
        	this.copyToolStripMenuItem.Size = new System.Drawing.Size(144, 22);
        	this.copyToolStripMenuItem.Text = "&Copy";
        	this.copyToolStripMenuItem.Click += new System.EventHandler(this.OnCopyToolStripMenuItemClick);
        	// 
        	// pasteToolStripMenuItem
        	// 
        	this.pasteToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("pasteToolStripMenuItem.Image")));
        	this.pasteToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
        	this.pasteToolStripMenuItem.Name = "pasteToolStripMenuItem";
        	this.pasteToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.V)));
        	this.pasteToolStripMenuItem.Size = new System.Drawing.Size(144, 22);
        	this.pasteToolStripMenuItem.Text = "&Paste";
        	this.pasteToolStripMenuItem.Click += new System.EventHandler(this.OnPasteToolStripMenuItemClick);
        	// 
        	// deleteToolStripMenuItem
        	// 
        	this.deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
        	this.deleteToolStripMenuItem.Size = new System.Drawing.Size(144, 22);
        	this.deleteToolStripMenuItem.Text = "&Delete";
        	this.deleteToolStripMenuItem.Click += new System.EventHandler(this.OnDeleteToolStripMenuItemClick);
        	// 
        	// toolStripSeparator5
        	// 
        	this.toolStripSeparator5.Name = "toolStripSeparator5";
        	this.toolStripSeparator5.Size = new System.Drawing.Size(141, 6);
        	// 
        	// selectAllToolStripMenuItem
        	// 
        	this.selectAllToolStripMenuItem.Name = "selectAllToolStripMenuItem";
        	this.selectAllToolStripMenuItem.Size = new System.Drawing.Size(144, 22);
        	this.selectAllToolStripMenuItem.Text = "Select &All";
        	this.selectAllToolStripMenuItem.Click += new System.EventHandler(this.OnSelectAllToolStripMenuItemClick);
        	// 
        	// optionsToolStripMenuItem
        	// 
        	this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.alwaysOnTopToolStripMenuItem,
        	        	        	this.closeBrowserToolStripMenuItem,
        	        	        	this.saveSettingsToolStripMenuItem});
        	this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
        	this.optionsToolStripMenuItem.Size = new System.Drawing.Size(61, 20);
        	this.optionsToolStripMenuItem.Text = "&Options";
        	this.optionsToolStripMenuItem.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.OnOptionsToolStripMenuItemDropDownItemClicked);
        	// 
        	// alwaysOnTopToolStripMenuItem
        	// 
        	this.alwaysOnTopToolStripMenuItem.Name = "alwaysOnTopToolStripMenuItem";
        	this.alwaysOnTopToolStripMenuItem.Size = new System.Drawing.Size(149, 22);
        	this.alwaysOnTopToolStripMenuItem.Text = "&Always on top";
        	// 
        	// closeBrowserToolStripMenuItem
        	// 
        	this.closeBrowserToolStripMenuItem.Name = "closeBrowserToolStripMenuItem";
        	this.closeBrowserToolStripMenuItem.Size = new System.Drawing.Size(149, 22);
        	this.closeBrowserToolStripMenuItem.Text = "&Close browser";
        	// 
        	// saveSettingsToolStripMenuItem
        	// 
        	this.saveSettingsToolStripMenuItem.Checked = true;
        	this.saveSettingsToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
        	this.saveSettingsToolStripMenuItem.Name = "saveSettingsToolStripMenuItem";
        	this.saveSettingsToolStripMenuItem.Size = new System.Drawing.Size(149, 22);
        	this.saveSettingsToolStripMenuItem.Text = "&Save settings";
        	// 
        	// helpToolStripMenuItem
        	// 
        	this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.moreReleasesPublicDomainGiftcomToolStripMenuItem,
        	        	        	this.originalThreadDonationCodercomToolStripMenuItem,
        	        	        	this.sourceCodeGithubcomToolStripMenuItem,
        	        	        	this.toolStripSeparator2,
        	        	        	this.aboutToolStripMenuItem});
        	this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
        	this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
        	this.helpToolStripMenuItem.Text = "&Help";
        	// 
        	// moreReleasesPublicDomainGiftcomToolStripMenuItem
        	// 
        	this.moreReleasesPublicDomainGiftcomToolStripMenuItem.Name = "moreReleasesPublicDomainGiftcomToolStripMenuItem";
        	this.moreReleasesPublicDomainGiftcomToolStripMenuItem.Size = new System.Drawing.Size(284, 22);
        	this.moreReleasesPublicDomainGiftcomToolStripMenuItem.Text = "More releases @ PublicDomainGift.com";
        	this.moreReleasesPublicDomainGiftcomToolStripMenuItem.Click += new System.EventHandler(this.OnMoreReleasesPublicDomainGiftomToolStripMenuItemClick);
        	// 
        	// originalThreadDonationCodercomToolStripMenuItem
        	// 
        	this.originalThreadDonationCodercomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("originalThreadDonationCodercomToolStripMenuItem.Image")));
        	this.originalThreadDonationCodercomToolStripMenuItem.Name = "originalThreadDonationCodercomToolStripMenuItem";
        	this.originalThreadDonationCodercomToolStripMenuItem.Size = new System.Drawing.Size(284, 22);
        	this.originalThreadDonationCodercomToolStripMenuItem.Text = "&Original thread @ DonationCoder.com";
        	this.originalThreadDonationCodercomToolStripMenuItem.Click += new System.EventHandler(this.OnOriginalThreadDonationCodercomToolStripMenuItemClick);
        	// 
        	// sourceCodeGithubcomToolStripMenuItem
        	// 
        	this.sourceCodeGithubcomToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("sourceCodeGithubcomToolStripMenuItem.Image")));
        	this.sourceCodeGithubcomToolStripMenuItem.Name = "sourceCodeGithubcomToolStripMenuItem";
        	this.sourceCodeGithubcomToolStripMenuItem.Size = new System.Drawing.Size(284, 22);
        	this.sourceCodeGithubcomToolStripMenuItem.Text = "Source code @ Github.com";
        	this.sourceCodeGithubcomToolStripMenuItem.Click += new System.EventHandler(this.OnSourceCodeGithubcomToolStripMenuItemClick);
        	// 
        	// toolStripSeparator2
        	// 
        	this.toolStripSeparator2.Name = "toolStripSeparator2";
        	this.toolStripSeparator2.Size = new System.Drawing.Size(281, 6);
        	// 
        	// aboutToolStripMenuItem
        	// 
        	this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
        	this.aboutToolStripMenuItem.Size = new System.Drawing.Size(284, 22);
        	this.aboutToolStripMenuItem.Text = "&About...";
        	this.aboutToolStripMenuItem.Click += new System.EventHandler(this.OnAboutToolStripMenuItemClick);
        	// 
        	// mainStatusStrip
        	// 
        	this.mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.mainToolStripStatusLabel,
        	        	        	this.lineCounToolStripStatusLabel});
        	this.mainStatusStrip.Location = new System.Drawing.Point(0, 340);
        	this.mainStatusStrip.Name = "mainStatusStrip";
        	this.mainStatusStrip.Size = new System.Drawing.Size(284, 22);
        	this.mainStatusStrip.SizingGrip = false;
        	this.mainStatusStrip.TabIndex = 22;
        	// 
        	// mainToolStripStatusLabel
        	// 
        	this.mainToolStripStatusLabel.Name = "mainToolStripStatusLabel";
        	this.mainToolStripStatusLabel.Size = new System.Drawing.Size(132, 17);
        	this.mainToolStripStatusLabel.Text = "Current lines in URL list:";
        	// 
        	// lineCounToolStripStatusLabel
        	// 
        	this.lineCounToolStripStatusLabel.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.lineCounToolStripStatusLabel.Name = "lineCounToolStripStatusLabel";
        	this.lineCounToolStripStatusLabel.Size = new System.Drawing.Size(14, 17);
        	this.lineCounToolStripStatusLabel.Text = "0";
        	// 
        	// mainTableLayoutPanel
        	// 
        	this.mainTableLayoutPanel.ColumnCount = 2;
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
        	this.mainTableLayoutPanel.Controls.Add(this.browseLabel, 0, 0);
        	this.mainTableLayoutPanel.Controls.Add(this.browserComboBox, 0, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.tableLayoutPanel2, 0, 4);
        	this.mainTableLayoutPanel.Controls.Add(this.intervalNumericUpDown, 1, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.label1, 1, 0);
        	this.mainTableLayoutPanel.Controls.Add(this.urlListtextBox, 0, 3);
        	this.mainTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.mainTableLayoutPanel.Location = new System.Drawing.Point(0, 24);
        	this.mainTableLayoutPanel.Name = "mainTableLayoutPanel";
        	this.mainTableLayoutPanel.RowCount = 5;
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 5F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 50F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
        	this.mainTableLayoutPanel.Size = new System.Drawing.Size(284, 316);
        	this.mainTableLayoutPanel.TabIndex = 24;
        	// 
        	// browseLabel
        	// 
        	this.browseLabel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.browseLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.browseLabel.Location = new System.Drawing.Point(3, 0);
        	this.browseLabel.Name = "browseLabel";
        	this.browseLabel.Size = new System.Drawing.Size(136, 25);
        	this.browseLabel.TabIndex = 0;
        	this.browseLabel.Text = "Browser:";
        	this.browseLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	// 
        	// browserComboBox
        	// 
        	this.browserComboBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.browserComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        	this.browserComboBox.FormattingEnabled = true;
        	this.browserComboBox.Items.AddRange(new object[] {
        	        	        	"Default",
        	        	        	"Edge"});
        	this.browserComboBox.Location = new System.Drawing.Point(3, 28);
        	this.browserComboBox.Name = "browserComboBox";
        	this.browserComboBox.Size = new System.Drawing.Size(136, 21);
        	this.browserComboBox.Sorted = true;
        	this.browserComboBox.TabIndex = 2;
        	// 
        	// tableLayoutPanel2
        	// 
        	this.tableLayoutPanel2.ColumnCount = 5;
        	this.mainTableLayoutPanel.SetColumnSpan(this.tableLayoutPanel2, 2);
        	this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28571F));
        	this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
        	this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
        	this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
        	this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 14.28572F));
        	this.tableLayoutPanel2.Controls.Add(this.beginButton, 0, 0);
        	this.tableLayoutPanel2.Controls.Add(this.backButton, 1, 0);
        	this.tableLayoutPanel2.Controls.Add(this.playButton, 2, 0);
        	this.tableLayoutPanel2.Controls.Add(this.nextButton, 3, 0);
        	this.tableLayoutPanel2.Controls.Add(this.endButton, 4, 0);
        	this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.tableLayoutPanel2.Location = new System.Drawing.Point(3, 269);
        	this.tableLayoutPanel2.Name = "tableLayoutPanel2";
        	this.tableLayoutPanel2.RowCount = 1;
        	this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
        	this.tableLayoutPanel2.Size = new System.Drawing.Size(278, 44);
        	this.tableLayoutPanel2.TabIndex = 7;
        	// 
        	// beginButton
        	// 
        	this.beginButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.beginButton.Image = ((System.Drawing.Image)(resources.GetObject("beginButton.Image")));
        	this.beginButton.Location = new System.Drawing.Point(2, 2);
        	this.beginButton.Margin = new System.Windows.Forms.Padding(2);
        	this.beginButton.Name = "beginButton";
        	this.beginButton.Size = new System.Drawing.Size(51, 40);
        	this.beginButton.TabIndex = 1;
        	this.beginButton.UseVisualStyleBackColor = true;
        	this.beginButton.Click += new System.EventHandler(this.OnBeginButtonClick);
        	// 
        	// backButton
        	// 
        	this.backButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.backButton.Image = ((System.Drawing.Image)(resources.GetObject("backButton.Image")));
        	this.backButton.Location = new System.Drawing.Point(57, 2);
        	this.backButton.Margin = new System.Windows.Forms.Padding(2);
        	this.backButton.Name = "backButton";
        	this.backButton.Size = new System.Drawing.Size(51, 40);
        	this.backButton.TabIndex = 2;
        	this.backButton.UseVisualStyleBackColor = true;
        	this.backButton.Click += new System.EventHandler(this.OnBackButtonClick);
        	// 
        	// playButton
        	// 
        	this.playButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.playButton.Image = ((System.Drawing.Image)(resources.GetObject("playButton.Image")));
        	this.playButton.Location = new System.Drawing.Point(112, 2);
        	this.playButton.Margin = new System.Windows.Forms.Padding(2);
        	this.playButton.Name = "playButton";
        	this.playButton.Size = new System.Drawing.Size(51, 40);
        	this.playButton.TabIndex = 3;
        	this.playButton.UseVisualStyleBackColor = true;
        	this.playButton.Click += new System.EventHandler(this.OnPlayButtonClick);
        	// 
        	// nextButton
        	// 
        	this.nextButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.nextButton.Image = ((System.Drawing.Image)(resources.GetObject("nextButton.Image")));
        	this.nextButton.Location = new System.Drawing.Point(167, 2);
        	this.nextButton.Margin = new System.Windows.Forms.Padding(2);
        	this.nextButton.Name = "nextButton";
        	this.nextButton.Size = new System.Drawing.Size(51, 40);
        	this.nextButton.TabIndex = 4;
        	this.nextButton.UseVisualStyleBackColor = true;
        	this.nextButton.Click += new System.EventHandler(this.OnNextButtonClick);
        	// 
        	// endButton
        	// 
        	this.endButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.endButton.Image = ((System.Drawing.Image)(resources.GetObject("endButton.Image")));
        	this.endButton.Location = new System.Drawing.Point(222, 2);
        	this.endButton.Margin = new System.Windows.Forms.Padding(2);
        	this.endButton.Name = "endButton";
        	this.endButton.Size = new System.Drawing.Size(54, 40);
        	this.endButton.TabIndex = 5;
        	this.endButton.UseVisualStyleBackColor = true;
        	this.endButton.Click += new System.EventHandler(this.OnEndButtonClick);
        	// 
        	// intervalNumericUpDown
        	// 
        	this.intervalNumericUpDown.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.intervalNumericUpDown.Location = new System.Drawing.Point(145, 28);
        	this.intervalNumericUpDown.Maximum = new decimal(new int[] {
        	        	        	1440,
        	        	        	0,
        	        	        	0,
        	        	        	0});
        	this.intervalNumericUpDown.Name = "intervalNumericUpDown";
        	this.intervalNumericUpDown.Size = new System.Drawing.Size(136, 20);
        	this.intervalNumericUpDown.TabIndex = 9;
        	this.intervalNumericUpDown.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
        	this.intervalNumericUpDown.Value = new decimal(new int[] {
        	        	        	1,
        	        	        	0,
        	        	        	0,
        	        	        	0});
        	this.intervalNumericUpDown.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.OnIntervalNumericUpDownKeyPress);
        	// 
        	// label1
        	// 
        	this.label1.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold);
        	this.label1.Location = new System.Drawing.Point(145, 0);
        	this.label1.Name = "label1";
        	this.label1.Size = new System.Drawing.Size(136, 25);
        	this.label1.TabIndex = 10;
        	this.label1.Text = "Line:";
        	this.label1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
        	// 
        	// urlListtextBox
        	// 
        	this.mainTableLayoutPanel.SetColumnSpan(this.urlListtextBox, 2);
        	this.urlListtextBox.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.urlListtextBox.Location = new System.Drawing.Point(3, 58);
        	this.urlListtextBox.Multiline = true;
        	this.urlListtextBox.Name = "urlListtextBox";
        	this.urlListtextBox.Size = new System.Drawing.Size(278, 205);
        	this.urlListtextBox.TabIndex = 11;
        	this.urlListtextBox.WordWrap = false;
        	this.urlListtextBox.TextChanged += new System.EventHandler(this.OnUrlListtextBoxTextChanged);
        	// 
        	// openFileDialog
        	// 
        	this.openFileDialog.DefaultExt = "txt";
        	this.openFileDialog.Filter = "TXT Files (*.txt)|*.txt|All files (*.*)|*.*";
        	this.openFileDialog.Title = "Open URLister file";
        	// 
        	// saveFileDialog
        	// 
        	this.saveFileDialog.DefaultExt = "txt";
        	this.saveFileDialog.Filter = "TXT Files (*.txt)|*.txt|All files (*.*)|*.*";
        	this.saveFileDialog.Title = "Save URLister file";
        	// 
        	// MainForm
        	// 
        	this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
        	this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        	this.ClientSize = new System.Drawing.Size(284, 362);
        	this.Controls.Add(this.mainTableLayoutPanel);
        	this.Controls.Add(this.mainMenuStrip);
        	this.Controls.Add(this.mainStatusStrip);
        	this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
        	this.Name = "MainForm";
        	this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        	this.Text = "Urlister";
        	this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.OnMainFormFormClosing);
        	this.mainMenuStrip.ResumeLayout(false);
        	this.mainMenuStrip.PerformLayout();
        	this.mainStatusStrip.ResumeLayout(false);
        	this.mainStatusStrip.PerformLayout();
        	this.mainTableLayoutPanel.ResumeLayout(false);
        	this.mainTableLayoutPanel.PerformLayout();
        	this.tableLayoutPanel2.ResumeLayout(false);
        	((System.ComponentModel.ISupportInitialize)(this.intervalNumericUpDown)).EndInit();
        	this.ResumeLayout(false);
        	this.PerformLayout();
        }
        private System.Windows.Forms.SaveFileDialog saveFileDialog;
        private System.Windows.Forms.OpenFileDialog openFileDialog;
        private System.Windows.Forms.ToolStripMenuItem alwaysOnTopToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveSettingsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem closeBrowserToolStripMenuItem;
        private System.Windows.Forms.TextBox urlListtextBox;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.NumericUpDown intervalNumericUpDown;
        private System.Windows.Forms.Button endButton;
        private System.Windows.Forms.Button nextButton;
        private System.Windows.Forms.Button playButton;
        private System.Windows.Forms.Button backButton;
        private System.Windows.Forms.Button beginButton;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.ComboBox browserComboBox;
        private System.Windows.Forms.Label browseLabel;
        private System.Windows.Forms.TableLayoutPanel mainTableLayoutPanel;
        private System.Windows.Forms.ToolStripStatusLabel lineCounToolStripStatusLabel;
        private System.Windows.Forms.ToolStripStatusLabel mainToolStripStatusLabel;
        private System.Windows.Forms.StatusStrip mainStatusStrip;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem sourceCodeGithubcomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem originalThreadDonationCodercomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem moreReleasesPublicDomainGiftcomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem selectAllToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator5;
        private System.Windows.Forms.ToolStripMenuItem deleteToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem pasteToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem copyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem cutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem saveAsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem saveToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator;
        private System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem newToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem minimizeToolStripMenuItem;
        private System.Windows.Forms.MenuStrip mainMenuStrip;
    }
}
